"""add image

Revision ID: 027ab8efd78a
Revises: 1f2c53e2a501
Create Date: 2025-03-21 16:28:14.601684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027ab8efd78a'
down_revision = '1f2c53e2a501'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'image')
    # ### end Alembic commands ###
